analyzer:
  errors:
    constant_identifier_names: ignore
    curly_braces_in_flow_control_structures: ignore
    must_be_immutable: ignore
    non_constant_identifier_names: ignore
include: package:flutter_lints/flutter.yaml
